CREATE TABLE GEOUSERS.SECTOR(
	IDSECTOR INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
)

CREATE TABLE GEOUSERS.RUBRO (
	IDRUBRO INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	IDSECTOR INT FOREIGN KEY REFERENCES GEOUSERS.SECTOR NOT NULL
)

CREATE TABLE GEOUSERS.TIPO_ORGANIZACION (
	IDTIPOORGANIZACION INT IDENTITY PRIMARY KEY,
	TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE GEOUSERS.LOCALIDAD (
	IDLOCALIDAD INT IDENTITY PRIMARY KEY,
	CODIGOPOSTAL INT UNIQUE NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE GEOUSERS.ORGANIZACION (
 IDORGANIZACION INT IDENTITY PRIMARY KEY,
 NOMBRE VARCHAR(50) NOT NULL, 
 DIRECCION VARCHAR(40) NOT NULL,
 TELEFONO VARCHAR(20) NOT NULL,
 CONTACTOCARGO VARCHAR(15) NOT NULL,
 EMAIL VARCHAR(25) NOT NULL,
 WEB VARCHAR(25),
 CUIT VARCHAR(15) UNIQUE,
 PERSONAL int,
 USUARIOINTI BIT NOT NULL,
 IDLOCALIDAD INT FOREIGN KEY REFERENCES GEOUSERS.LOCALIDAD NOT NULL,
 IDTIPOORGANIZACION INT FOREIGN KEY REFERENCES GEOUSERS.ORGANIZACION NOT NULL,
 IDRUBRO INT FOREIGN KEY REFERENCES GEOUSERS.RUBRO NOT NULL
);


--TODO

--CREATE TABLE GEOUSERS.USUARIO (
-- IDUSUARIO INT IDENTITY PRIMARY KEY,
-- NOMBRE VARCHAR(50) NOT NULL, 
-- CLAVE VARCHAR(30) NOT NULL
--);

--CREATE TABLE GEOUSERS.USUARIO_PERMISO (
-- IDUSUARIOPERMISO INT IDENTITY PRIMARY KEY,
-- IDUSUARIO INT,
-- IDPERMISO INT
--);

--CREATE TABLE GEOUSERS.USUARIO_CONFIG (
-- IDCONFIG INT IDENTITY PRIMARY KEY,
-- IDUSUARIO VARCHAR(50) NOT NULL, 
-- COLORMENU VARCHAR(15),
--);
