CREATE USER SGUADMIN IDENTIFIED BY 'SGUADMIN001';

GRANT ALL ON SGU.USUARIO TO SGUADMIN;
GRANT ALL ON SGU.LOCALIDAD TO SGUADMIN;
GRANT ALL ON SGU.SECTOR TO SGUADMIN;
GRANT ALL ON SGU.RUBRO TO SGUADMIN;
GRANT ALL ON SGU.ORGANIZACION TO SGUADMIN;
GRANT ALL ON SGU.ARCHIVO TO SGUADMIN;
GRANT ALL ON SGU.TIPOORGANIZACION TO SGUADMIN;