CREATE DATABASE SGU;

CREATE TABLE SGU.USUARIO (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    LOGINID VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE SGU.ARCHIVO (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	RUTA VARCHAR(260),
	NOMBRE VARCHAR(50),
	EXTENSION VARCHAR(5) NOT NULL    
);

CREATE TABLE SGU.SECTOR(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	IDICONO INT
);

ALTER TABLE SGU.SECTOR 
ADD CONSTRAINT FK_SECTOR_ICONO 
FOREIGN KEY (IDICONO) 
REFERENCES SGU.ARCHIVO (ID)
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

CREATE TABLE SGU.RUBRO (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	IDSECTOR INT NOT NULL
);

ALTER TABLE SGU.RUBRO 
ADD CONSTRAINT FK_RUBRO_SECTOR 
FOREIGN KEY (IDSECTOR) 
REFERENCES SGU.SECTOR (ID)
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

CREATE TABLE SGU.TIPOORGANIZACION (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE SGU.LOCALIDAD (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CODIGOPOSTAL INT UNIQUE NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE SGU.ORGANIZACION (
 ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
 NOMBRE VARCHAR(50) NOT NULL, 
 DIRECCION VARCHAR(40) NOT NULL,
 TELEFONO VARCHAR(20) NOT NULL,
 CONTACTOCARGO VARCHAR(15) NOT NULL,
 EMAIL VARCHAR(25) NOT NULL,
 WEB VARCHAR(25),
 CUIT BIGINT UNIQUE,
 PERSONAL INT,
 USUARIOINTI BIT NOT NULL,
 LATITUD VARCHAR(50),
 LONGITUD VARCHAR(50),
 IDLOCALIDAD INT NOT NULL,
 IDTIPOORGANIZACION INT NOT NULL,
 IDRUBRO INT NOT NULL
);

ALTER TABLE SGU.ORGANIZACION 
ADD CONSTRAINT FK_ORGANIZACION_RUBRO 
FOREIGN KEY (IDRUBRO) 
REFERENCES SGU.RUBRO (ID)
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE SGU.ORGANIZACION 
ADD CONSTRAINT FK_ORGANIZACION_TIPO 
FOREIGN KEY (IDTIPOORGANIZACION) 
REFERENCES SGU.TIPOORGANIZACION (ID)
ON UPDATE NO ACTION 
ON DELETE NO ACTION;

ALTER TABLE SGU.ORGANIZACION 
ADD CONSTRAINT FK_ORGANIZACION_LOCALIDAD
FOREIGN KEY (IDLOCALIDAD) 
REFERENCES SGU.LOCALIDAD (ID)
ON UPDATE NO ACTION 
ON DELETE NO ACTION;


