INSERT INTO SGU.USUARIO (LOGINID, PASSWORD) 
VALUES ('SGUADMIN','8V+3hUNHXKC3rlgieWA7/00KQg2/ci1E2xeyjEYksy1u3tdbMLztcIQMAshu3pHP2NgdS9tcirU/GVQTlj8tIf7Lx2nbBZNsvrYPiXqcHAQVQO4OfG1ytcjEaSdhGX2j');

COMMIT;